apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: ServiceNow cluster role for confined access to view OpenShift resources.
    openshift.io/reconcile-protect: "false"
  name: servicenow-view
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - services
  verbs:
  - get
  - list
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - nodes
  verbs:
  - get
  - list